// This file was automatically generated.  Do not modify.

'use strict';

Blockly.Msg["ADD_COMMENT"] = "添加注释";
Blockly.Msg["CANNOT_DELETE_VARIABLE_PROCEDURE"] = "不能删除变量“%1”，因为它是函数“%2”定义的一部分";
Blockly.Msg["CHANGE_VALUE_TITLE"] = "更改值：";
Blockly.Msg["CLEAN_UP"] = "整理块";
Blockly.Msg["COLLAPSED_WARNINGS_WARNING"] = "已收起的信息块内包含警告。";
Blockly.Msg["COLLAPSE_ALL"] = "折叠块";
Blockly.Msg["COLLAPSE_BLOCK"] = "折叠块";
Blockly.Msg["COLOUR_BLEND_COLOUR1"] = "颜色1";
Blockly.Msg["COLOUR_BLEND_COLOUR2"] = "颜色2";
Blockly.Msg["COLOUR_BLEND_HELPURL"] = "https://meyerweb.com/eric/tools/color-blend/#:::rgbp";  // untranslated
Blockly.Msg["COLOUR_BLEND_RATIO"] = "比例";
Blockly.Msg["COLOUR_BLEND_TITLE"] = "混合";
Blockly.Msg["COLOUR_BLEND_TOOLTIP"] = "把两种颜色以一个给定的比例(0.0-1.0)进行混合。";
Blockly.Msg["COLOUR_PICKER_HELPURL"] = "https://zh.wikipedia.org/wiki/颜色";
Blockly.Msg["COLOUR_PICKER_TOOLTIP"] = "从调色板中选择一种颜色。";
Blockly.Msg["COLOUR_RANDOM_HELPURL"] = "http://randomcolour.com";  // untranslated
Blockly.Msg["COLOUR_RANDOM_TITLE"] = "随机颜色";
Blockly.Msg["COLOUR_RANDOM_TOOLTIP"] = "随机选择一种颜色。";
Blockly.Msg["COLOUR_RGB_BLUE"] = "蓝色";
Blockly.Msg["COLOUR_RGB_GREEN"] = "绿色";
Blockly.Msg["COLOUR_RGB_HELPURL"] = "https://www.december.com/html/spec/colorpercompact.html";  // untranslated
Blockly.Msg["COLOUR_RGB_RED"] = "红色";
Blockly.Msg["COLOUR_RGB_TITLE"] = "颜色";
Blockly.Msg["COLOUR_RGB_TOOLTIP"] = "通过指定红色、绿色和蓝色的量创建一种颜色。所有的值必须在0和100之间。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK"] = "跳出循环";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE"] = "继续下一轮循环";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK"] = "跳出包含它的循环。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE"] = "跳过本轮循环的剩余部分，并继进行续下一轮迭代。";
Blockly.Msg["CONTROLS_FLOW_STATEMENTS_WARNING"] = "警告：这个块只能在循环内使用。";
Blockly.Msg["CONTROLS_FOREACH_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg["CONTROLS_FOREACH_TITLE"] = "为列表 %2 里的每一项 %1";
Blockly.Msg["CONTROLS_FOREACH_TOOLTIP"] = "遍历列表中的每一项，将变量“%1”设为所选项，并执行一些语句。";
Blockly.Msg["CONTROLS_FOR_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg["CONTROLS_FOR_TITLE"] = "变量 %1 从 %2 数到 %3 每次增加 %4";
Blockly.Msg["CONTROLS_FOR_TOOLTIP"] = "用变量%1记录从开始数值到终止数值之间的数值，数值按指定间隔增加，并执行指定的块。";
Blockly.Msg["CONTROLS_IF_ELSEIF_TOOLTIP"] = "在这个if语句块中增加一个条件。";
Blockly.Msg["CONTROLS_IF_ELSE_TOOLTIP"] = "在这个if语句块中添加一个最终的，包括所有其余情况的条件。";
Blockly.Msg["CONTROLS_IF_HELPURL"] = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg["CONTROLS_IF_IF_TOOLTIP"] = "增加、删除或重新排列各节来重新配置这个if语句块。";
Blockly.Msg["CONTROLS_IF_MSG_ELSE"] = "否则";
Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"] = "否则如果";
Blockly.Msg["CONTROLS_IF_MSG_IF"] = "如果";
Blockly.Msg["CONTROLS_IF_TOOLTIP_1"] = "如果值为真，执行一些语句。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_2"] = "如果值为真，则执行第一块语句。否则，则执行第二块语句。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_3"] = "如果第一个值为真，则执行第一块的语句。否则，如果第二个值为真，则执行第二块的语句。";
Blockly.Msg["CONTROLS_IF_TOOLTIP_4"] = "如果第一个值为真，则执行第一块对语句。否则，如果第二个值为真，则执行语句的第二块。如果没有值为真，则执行最后一块的语句。";
Blockly.Msg["CONTROLS_REPEAT_HELPURL"] = "https://zh.wikipedia.org/wiki/For循环";
Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"] = "执行";
Blockly.Msg["CONTROLS_REPEAT_TITLE"] = "重复 %1 次";
Blockly.Msg["CONTROLS_REPEAT_TOOLTIP"] = "多次执行一些语句。";
Blockly.Msg["CONTROLS_WHILEUNTIL_HELPURL"] = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_UNTIL"] = "重复直到条件满足";
Blockly.Msg["CONTROLS_WHILEUNTIL_OPERATOR_WHILE"] = "当条件满足时重复";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL"] = "只要值为假，执行一些语句。";
Blockly.Msg["CONTROLS_WHILEUNTIL_TOOLTIP_WHILE"] = "只要值为真，执行一些语句。";
Blockly.Msg["DELETE_ALL_BLOCKS"] = "删除所有 %1 个块吗？";
Blockly.Msg["DELETE_BLOCK"] = "删除块";
Blockly.Msg["DELETE_VARIABLE"] = "删除变量“%1”";
Blockly.Msg["DELETE_VARIABLE_CONFIRMATION"] = "要删除对变量“%2”的%1个引用吗？";
Blockly.Msg["DELETE_X_BLOCKS"] = "删除 %1 个块";
Blockly.Msg["DISABLE_BLOCK"] = "禁用块";
Blockly.Msg["DUPLICATE_BLOCK"] = "复制";
Blockly.Msg["DUPLICATE_COMMENT"] = "复制注释";
Blockly.Msg["ENABLE_BLOCK"] = "启用块";
Blockly.Msg["EXPAND_ALL"] = "展开块";
Blockly.Msg["EXPAND_BLOCK"] = "展开块";
Blockly.Msg["EXTERNAL_INPUTS"] = "外部输入";
Blockly.Msg["HELP"] = "帮助";
Blockly.Msg["INLINE_INPUTS"] = "单行输入";
Blockly.Msg["IOS_CANCEL"] = "取消";
Blockly.Msg["IOS_ERROR"] = "错误";
Blockly.Msg["IOS_OK"] = "确定";
Blockly.Msg["IOS_PROCEDURES_ADD_INPUT"] = "+添加输入";
Blockly.Msg["IOS_PROCEDURES_ALLOW_STATEMENTS"] = "允许的语句";
Blockly.Msg["IOS_PROCEDURES_DUPLICATE_INPUTS_ERROR"] = "这个函数有多个输入。";
Blockly.Msg["IOS_PROCEDURES_INPUTS"] = "输入";
Blockly.Msg["IOS_VARIABLES_ADD_BUTTON"] = "添加";
Blockly.Msg["IOS_VARIABLES_ADD_VARIABLE"] = "+添加变量";
Blockly.Msg["IOS_VARIABLES_DELETE_BUTTON"] = "删除";
Blockly.Msg["IOS_VARIABLES_EMPTY_NAME_ERROR"] = "你不能使用空白的变量名。";
Blockly.Msg["IOS_VARIABLES_RENAME_BUTTON"] = "重命名";
Blockly.Msg["IOS_VARIABLES_VARIABLE_NAME"] = "变量名";
Blockly.Msg["LISTS_CREATE_EMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
Blockly.Msg["LISTS_CREATE_EMPTY_TITLE"] = "创建空列表";
Blockly.Msg["LISTS_CREATE_EMPTY_TOOLTIP"] = "返回一个列表，长度为 0，不包含任何数据记录";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TITLE_ADD"] = "列表";
Blockly.Msg["LISTS_CREATE_WITH_CONTAINER_TOOLTIP"] = "增加、删除或重新排列各部分以此重新配置这个列表块。";
Blockly.Msg["LISTS_CREATE_WITH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg["LISTS_CREATE_WITH_INPUT_WITH"] = "建立列表从";
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TOOLTIP"] = "将一个项添加到列表中。";
Blockly.Msg["LISTS_CREATE_WITH_TOOLTIP"] = "建立一个具有任意数量项目的列表。";
Blockly.Msg["LISTS_GET_INDEX_FIRST"] = "第一个";
Blockly.Msg["LISTS_GET_INDEX_FROM_END"] = "倒数第#";
Blockly.Msg["LISTS_GET_INDEX_FROM_START"] = "#";
Blockly.Msg["LISTS_GET_INDEX_GET"] = "取得";
Blockly.Msg["LISTS_GET_INDEX_GET_REMOVE"] = "取得并移除";
Blockly.Msg["LISTS_GET_INDEX_LAST"] = "最后一个";
Blockly.Msg["LISTS_GET_INDEX_RANDOM"] = "随机的";
Blockly.Msg["LISTS_GET_INDEX_REMOVE"] = "移除";
Blockly.Msg["LISTS_GET_INDEX_TAIL"] = "-";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FIRST"] = "返回列表中的第一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_FROM"] = "返回在列表中的指定位置的项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_LAST"] = "返回列表中的最后一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_RANDOM"] = "返回列表中的随机一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST"] = "移除并返回列表中的第一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM"] = "移除并返回列表中的指定位置的项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST"] = "移除并返回列表中的最后一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM"] = "移除并返回列表中的随机一项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST"] = "移除列表中的第一项";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM"] = "移除在列表中的指定位置的项。";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST"] = "移除列表中的最后一项";
Blockly.Msg["LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM"] = "删除列表中的随机一项。";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_END"] = "到倒数第#";
Blockly.Msg["LISTS_GET_SUBLIST_END_FROM_START"] = "到#";
Blockly.Msg["LISTS_GET_SUBLIST_END_LAST"] = "到最后";
Blockly.Msg["LISTS_GET_SUBLIST_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg["LISTS_GET_SUBLIST_START_FIRST"] = "获取子列表从第一个";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_END"] = "获取子列表从最后一个#";
Blockly.Msg["LISTS_GET_SUBLIST_START_FROM_START"] = "获取子列表从#";
Blockly.Msg["LISTS_GET_SUBLIST_TAIL"] = "-";
Blockly.Msg["LISTS_GET_SUBLIST_TOOLTIP"] = "复制列表中指定的部分。";
Blockly.Msg["LISTS_INDEX_FROM_END_TOOLTIP"] = "%1是最后一项。";
Blockly.Msg["LISTS_INDEX_FROM_START_TOOLTIP"] = "%1是第一项。";
Blockly.Msg["LISTS_INDEX_OF_FIRST"] = "寻找第一次出现的项";
Blockly.Msg["LISTS_INDEX_OF_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg["LISTS_INDEX_OF_LAST"] = "寻找最后一次出现的项";
Blockly.Msg["LISTS_INDEX_OF_TOOLTIP"] = "返回在列表中的第一/最后一个匹配项的索引值。如果找不到项目则返回%1。";
Blockly.Msg["LISTS_INLIST"] = "在列表中";
Blockly.Msg["LISTS_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg["LISTS_ISEMPTY_TITLE"] = "%1是空的";
Blockly.Msg["LISTS_ISEMPTY_TOOLTIP"] = "如果该列表为空，则返回真。";
Blockly.Msg["LISTS_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg["LISTS_LENGTH_TITLE"] = "%1的长度";
Blockly.Msg["LISTS_LENGTH_TOOLTIP"] = "返回列表的长度。";
Blockly.Msg["LISTS_REPEAT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg["LISTS_REPEAT_TITLE"] = "建立列表使用项 %1 重复 %2 次";
Blockly.Msg["LISTS_REPEAT_TOOLTIP"] = "建立包含指定重复次数的值的列表。";
Blockly.Msg["LISTS_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#reversing-a-list";
Blockly.Msg["LISTS_REVERSE_MESSAGE0"] = "倒转%1";
Blockly.Msg["LISTS_REVERSE_TOOLTIP"] = "倒转一个列表的拷贝。";
Blockly.Msg["LISTS_SET_INDEX_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg["LISTS_SET_INDEX_INPUT_TO"] = "值为";
Blockly.Msg["LISTS_SET_INDEX_INSERT"] = "插入在";
Blockly.Msg["LISTS_SET_INDEX_SET"] = "设置";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST"] = "在列表的起始处添加该项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_FROM"] = "插入在列表中指定位置的项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_LAST"] = "在列表的末尾处添加该项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM"] = "在列表的随机位置插入该项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FIRST"] = "设置列表中的第一项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_FROM"] = "设置在列表中指定位置的项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_LAST"] = "设置列表中的最后一项。";
Blockly.Msg["LISTS_SET_INDEX_TOOLTIP_SET_RANDOM"] = "设置列表中的随机一项。";
Blockly.Msg["LISTS_SORT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg["LISTS_SORT_ORDER_ASCENDING"] = "升序";
Blockly.Msg["LISTS_SORT_ORDER_DESCENDING"] = "降序";
Blockly.Msg["LISTS_SORT_TITLE"] = "排序%1 %2 %3";
Blockly.Msg["LISTS_SORT_TOOLTIP"] = "排序一个列表的拷贝。";
Blockly.Msg["LISTS_SORT_TYPE_IGNORECASE"] = "按字母排序，忽略大小写";
Blockly.Msg["LISTS_SORT_TYPE_NUMERIC"] = "按数字排序";
Blockly.Msg["LISTS_SORT_TYPE_TEXT"] = "按字母排序";
Blockly.Msg["LISTS_SPLIT_HELPURL"] = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg["LISTS_SPLIT_LIST_FROM_TEXT"] = "从文本制作列表";
Blockly.Msg["LISTS_SPLIT_TEXT_FROM_LIST"] = "从列表拆出文本";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_JOIN"] = "加入文本列表至一个文本，由分隔符分隔。";
Blockly.Msg["LISTS_SPLIT_TOOLTIP_SPLIT"] = "拆分文本到文本列表，按每个分隔符拆分。";
Blockly.Msg["LISTS_SPLIT_WITH_DELIMITER"] = "用分隔符";
Blockly.Msg["LOGIC_BOOLEAN_FALSE"] = "假";
Blockly.Msg["LOGIC_BOOLEAN_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg["LOGIC_BOOLEAN_TOOLTIP"] = "返回真或假。";
Blockly.Msg["LOGIC_BOOLEAN_TRUE"] = "真";
Blockly.Msg["LOGIC_COMPARE_HELPURL"] = "https://zh.wikipedia.org/wiki/不等";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_EQ"] = "如果两个输入结果相等，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GT"] = "如果第一个输入结果比第二个大，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_GTE"] = "如果第一个输入结果大于或等于第二个输入结果，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LT"] = "如果第一个输入结果比第二个小，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_LTE"] = "如果第一个输入结果小于或等于第二个输入结果，则返回真。";
Blockly.Msg["LOGIC_COMPARE_TOOLTIP_NEQ"] = "如果两个输入结果不相等，则返回真。";
Blockly.Msg["LOGIC_NEGATE_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg["LOGIC_NEGATE_TITLE"] = "非%1";
Blockly.Msg["LOGIC_NEGATE_TOOLTIP"] = "如果输入结果为假，则返回真；如果输入结果为真，则返回假。";
Blockly.Msg["LOGIC_NULL"] = "空";
Blockly.Msg["LOGIC_NULL_HELPURL"] = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg["LOGIC_NULL_TOOLTIP"] = "返回空值。";
Blockly.Msg["LOGIC_OPERATION_AND"] = "并且";
Blockly.Msg["LOGIC_OPERATION_HELPURL"] = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg["LOGIC_OPERATION_OR"] = "或";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_AND"] = "如果两个输入结果都为真，则返回真。";
Blockly.Msg["LOGIC_OPERATION_TOOLTIP_OR"] = "如果至少有一个输入结果为真，则返回真。";
Blockly.Msg["LOGIC_TERNARY_CONDITION"] = "断言";
Blockly.Msg["LOGIC_TERNARY_HELPURL"] = "https://zh.wikipedia.org/wiki/条件运算符";
Blockly.Msg["LOGIC_TERNARY_IF_FALSE"] = "如果为假";
Blockly.Msg["LOGIC_TERNARY_IF_TRUE"] = "如果为真";
Blockly.Msg["LOGIC_TERNARY_TOOLTIP"] = "检查“断言”里的条件语句。如果条件为真，则返回“如果为真”的值，否则，则返回“如果为假”的值。";
Blockly.Msg["MATH_ADDITION_SYMBOL"] = "+";  // untranslated
Blockly.Msg["MATH_ARITHMETIC_HELPURL"] = "https://zh.wikipedia.org/wiki/算术";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_ADD"] = "返回两个数值的和。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_DIVIDE"] = "返回两个数值的商。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MINUS"] = "返回两个数值的差值。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_MULTIPLY"] = "返回两个数值的乘积。";
Blockly.Msg["MATH_ARITHMETIC_TOOLTIP_POWER"] = "返回以第一个数值为底数，以第二个数值为幂的结果。";
Blockly.Msg["MATH_ATAN2_HELPURL"] = "https://zh.wikipedia.org/wiki/反正切2";
Blockly.Msg["MATH_ATAN2_TITLE"] = "点(x:%1,y:%2)的方位角";
Blockly.Msg["MATH_ATAN2_TOOLTIP"] = "返回点（X，Y）的反正切值，范围为-180到180度。";
Blockly.Msg["MATH_CHANGE_HELPURL"] = "https://zh.wikipedia.org/wiki/加法";
Blockly.Msg["MATH_CHANGE_TITLE"] = "将 %1 增加 %2";
Blockly.Msg["MATH_CHANGE_TOOLTIP"] = "为变量“%1”增加一个数值。";
Blockly.Msg["MATH_CONSTANT_HELPURL"] = "https://zh.wikipedia.org/wiki/数学常数";
Blockly.Msg["MATH_CONSTANT_TOOLTIP"] = "返回一个常见常量：π (3.141…)、e (2.718…)、φ (1.618…)、平方根 (1.414…)、开平方根 (0.707…)或∞ (无限大)。";
Blockly.Msg["MATH_CONSTRAIN_HELPURL"] = "https://en.wikipedia.org/wiki/Clamping_(graphics)";  // untranslated
Blockly.Msg["MATH_CONSTRAIN_TITLE"] = "将 %1 限制在 最低 %2 到最高 %3 之间";
Blockly.Msg["MATH_CONSTRAIN_TOOLTIP"] = "将一个数值限制在两个指定的数值范围（含边界）之间。";
Blockly.Msg["MATH_DIVISION_SYMBOL"] = "÷";  // untranslated
Blockly.Msg["MATH_IS_DIVISIBLE_BY"] = "可被整除";
Blockly.Msg["MATH_IS_EVEN"] = "是偶数";
Blockly.Msg["MATH_IS_NEGATIVE"] = "是负数";
Blockly.Msg["MATH_IS_ODD"] = "是奇数";
Blockly.Msg["MATH_IS_POSITIVE"] = "是正数";
Blockly.Msg["MATH_IS_PRIME"] = "是质数";
Blockly.Msg["MATH_IS_TOOLTIP"] = "检查一个数值是否是偶数、奇数、质数、自然数、正数、负数或者是否能被某数整除。返回真或假。";
Blockly.Msg["MATH_IS_WHOLE"] = "是整数";
Blockly.Msg["MATH_MODULO_HELPURL"] = "https://zh.wikipedia.org/wiki/模除";
Blockly.Msg["MATH_MODULO_TITLE"] = "取 %1 ÷ %2 的余数";
Blockly.Msg["MATH_MODULO_TOOLTIP"] = "返回这两个数字相除后的余数。";
Blockly.Msg["MATH_MULTIPLICATION_SYMBOL"] = "×";  // untranslated
Blockly.Msg["MATH_NUMBER_HELPURL"] = "https://zh.wikipedia.org/wiki/数";
Blockly.Msg["MATH_NUMBER_TOOLTIP"] = "一个数值。";
Blockly.Msg["MATH_ONLIST_HELPURL"] = "";  // untranslated
Blockly.Msg["MATH_ONLIST_OPERATOR_AVERAGE"] = "列表平均值";
Blockly.Msg["MATH_ONLIST_OPERATOR_MAX"] = "列表最大值";
Blockly.Msg["MATH_ONLIST_OPERATOR_MEDIAN"] = "列表中位数";
Blockly.Msg["MATH_ONLIST_OPERATOR_MIN"] = "列表最小值";
Blockly.Msg["MATH_ONLIST_OPERATOR_MODE"] = "列表中的众数";
Blockly.Msg["MATH_ONLIST_OPERATOR_RANDOM"] = "列表随机项";
Blockly.Msg["MATH_ONLIST_OPERATOR_STD_DEV"] = "列表的标准差";
Blockly.Msg["MATH_ONLIST_OPERATOR_SUM"] = "列表中数值的和";
Blockly.Msg["MATH_ONLIST_TOOLTIP_AVERAGE"] = "返回列表中的数值的平均值。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MAX"] = "返回列表中最大值。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MEDIAN"] = "返回列表中数值的中位数。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MIN"] = "返回列表中最小值。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_MODE"] = "返回列表中的出现次数最多的项的列表。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_RANDOM"] = "从列表中返回一个随机的元素。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_STD_DEV"] = "返回列表的标准差。";
Blockly.Msg["MATH_ONLIST_TOOLTIP_SUM"] = "返回列表中的所有数值的和。";
Blockly.Msg["MATH_POWER_SYMBOL"] = "^";  // untranslated
Blockly.Msg["MATH_RANDOM_FLOAT_HELPURL"] = "https://zh.wikipedia.org/wiki/随机数生成器";
Blockly.Msg["MATH_RANDOM_FLOAT_TITLE_RANDOM"] = "随机小数";
Blockly.Msg["MATH_RANDOM_FLOAT_TOOLTIP"] = "返回一个介于0.0到1.0之间（含边界）的随机数。";
Blockly.Msg["MATH_RANDOM_INT_HELPURL"] = "https://zh.wikipedia.org/wiki/随机数生成器";
Blockly.Msg["MATH_RANDOM_INT_TITLE"] = "从 %1 到 %2 范围内的随机整数";
Blockly.Msg["MATH_RANDOM_INT_TOOLTIP"] = "返回一个限制在两个指定数值的范围（含边界）之间的随机整数。";
Blockly.Msg["MATH_ROUND_HELPURL"] = "https://zh.wikipedia.org/wiki/数值修约";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUND"] = "四舍五入";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDDOWN"] = "向下舍入";
Blockly.Msg["MATH_ROUND_OPERATOR_ROUNDUP"] = "向上舍入";
Blockly.Msg["MATH_ROUND_TOOLTIP"] = "数字向上或向下舍入。";
Blockly.Msg["MATH_SINGLE_HELPURL"] = "https://zh.wikipedia.org/wiki/平方根";
Blockly.Msg["MATH_SINGLE_OP_ABSOLUTE"] = "绝对值";
Blockly.Msg["MATH_SINGLE_OP_ROOT"] = "平方根";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ABS"] = "返回一个数值的绝对值。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_EXP"] = "返回一个数值的e次幂。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LN"] = "返回一个数值的自然对数。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_LOG10"] = "返回一个数值的以10为底的对数。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_NEG"] = "返回一个数值的相反数。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_POW10"] = "返回一个数值的10次幂。";
Blockly.Msg["MATH_SINGLE_TOOLTIP_ROOT"] = "返回一个数的平方根。";
Blockly.Msg["MATH_SUBTRACTION_SYMBOL"] = "-";  // untranslated
Blockly.Msg["MATH_TRIG_ACOS"] = "acos";  // untranslated
Blockly.Msg["MATH_TRIG_ASIN"] = "asin";  // untranslated
Blockly.Msg["MATH_TRIG_ATAN"] = "atan";  // untranslated
Blockly.Msg["MATH_TRIG_COS"] = "cos";  // untranslated
Blockly.Msg["MATH_TRIG_HELPURL"] = "https://zh.wikipedia.org/wiki/三角函数";
Blockly.Msg["MATH_TRIG_SIN"] = "sin";  // untranslated
Blockly.Msg["MATH_TRIG_TAN"] = "tan";  // untranslated
Blockly.Msg["MATH_TRIG_TOOLTIP_ACOS"] = "返回一个数值的反余弦值。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ASIN"] = "返回一个数值的反正弦值。";
Blockly.Msg["MATH_TRIG_TOOLTIP_ATAN"] = "返回一个数值的反正切值。";
Blockly.Msg["MATH_TRIG_TOOLTIP_COS"] = "返回指定角度的余弦值(非弧度）。";
Blockly.Msg["MATH_TRIG_TOOLTIP_SIN"] = "返回指定角度的正弦值(非弧度）。";
Blockly.Msg["MATH_TRIG_TOOLTIP_TAN"] = "返回指定角度的正切值(非弧度）。";
Blockly.Msg["NEW_COLOUR_VARIABLE"] = "创建颜色变量...";
Blockly.Msg["NEW_NUMBER_VARIABLE"] = "创建数字变量...";
Blockly.Msg["NEW_STRING_VARIABLE"] = "创建字符串变量...";
Blockly.Msg["NEW_VARIABLE"] = "创建变量...";
Blockly.Msg["NEW_VARIABLE_TITLE"] = "新变量的名称：";
Blockly.Msg["NEW_VARIABLE_TYPE_TITLE"] = "新变量的类型：";
Blockly.Msg["ORDINAL_NUMBER_SUFFIX"] = "-";
Blockly.Msg["PROCEDURES_ALLOW_STATEMENTS"] = "允许声明";
Blockly.Msg["PROCEDURES_BEFORE_PARAMS"] = "与：";
Blockly.Msg["PROCEDURES_CALLNORETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg["PROCEDURES_CALLNORETURN_TOOLTIP"] = "运行用户定义的函数“%1”。";
Blockly.Msg["PROCEDURES_CALLRETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg["PROCEDURES_CALLRETURN_TOOLTIP"] = "运行用户定义的函数“%1”，并使用它的输出值。";
Blockly.Msg["PROCEDURES_CALL_BEFORE_PARAMS"] = "与：";
Blockly.Msg["PROCEDURES_CREATE_DO"] = "创建“%1”";
Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"] = "描述该功能...";
Blockly.Msg["PROCEDURES_DEFNORETURN_DO"] = "-";
Blockly.Msg["PROCEDURES_DEFNORETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"] = "做点什么";
Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"] = "至";
Blockly.Msg["PROCEDURES_DEFNORETURN_TOOLTIP"] = "创建一个不带输出值的函数。";
Blockly.Msg["PROCEDURES_DEFRETURN_HELPURL"] = "https://zh.wikipedia.org/wiki/子程序";
Blockly.Msg["PROCEDURES_DEFRETURN_RETURN"] = "返回";
Blockly.Msg["PROCEDURES_DEFRETURN_TOOLTIP"] = "创建一个有输出值的函数。";
Blockly.Msg["PROCEDURES_DEF_DUPLICATE_WARNING"] = "警告：此函数具有重复参数。";
Blockly.Msg["PROCEDURES_HIGHLIGHT_DEF"] = "突出显示函数定义";
Blockly.Msg["PROCEDURES_IFRETURN_HELPURL"] = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg["PROCEDURES_IFRETURN_TOOLTIP"] = "如果值为真，则返回第二个值。";
Blockly.Msg["PROCEDURES_IFRETURN_WARNING"] = "警告：这个块只能在函数内部使用。";
Blockly.Msg["PROCEDURES_MUTATORARG_TITLE"] = "输入名称：";
Blockly.Msg["PROCEDURES_MUTATORARG_TOOLTIP"] = "添加函数输入。";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TITLE"] = "输入";
Blockly.Msg["PROCEDURES_MUTATORCONTAINER_TOOLTIP"] = "添加、移除或重新排此函数的输入。";
Blockly.Msg["REDO"] = "重做";
Blockly.Msg["REMOVE_COMMENT"] = "删除注释";
Blockly.Msg["RENAME_VARIABLE"] = "重命名变量...";
Blockly.Msg["RENAME_VARIABLE_TITLE"] = "将所有“%1”变量重命名为:";
Blockly.Msg["TEXT_APPEND_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_APPEND_TITLE"] = "向%1附加文本%2";
Blockly.Msg["TEXT_APPEND_TOOLTIP"] = "将一些文本追加到变量“%1”里。";
Blockly.Msg["TEXT_CHANGECASE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_LOWERCASE"] = "转为小写";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_TITLECASE"] = "转为首字母大写";
Blockly.Msg["TEXT_CHANGECASE_OPERATOR_UPPERCASE"] = "转为大写";
Blockly.Msg["TEXT_CHANGECASE_TOOLTIP"] = "用不同的大小写模式复制并返回这段文字。";
Blockly.Msg["TEXT_CHARAT_FIRST"] = "寻找第一个字母";
Blockly.Msg["TEXT_CHARAT_FROM_END"] = "获取字符从倒数#";
Blockly.Msg["TEXT_CHARAT_FROM_START"] = "获取字符从#";
Blockly.Msg["TEXT_CHARAT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg["TEXT_CHARAT_LAST"] = "寻找最后一个字母";
Blockly.Msg["TEXT_CHARAT_RANDOM"] = "寻找随机的字母";
Blockly.Msg["TEXT_CHARAT_TAIL"] = "-";
Blockly.Msg["TEXT_CHARAT_TITLE"] = "在文本%1 里 %2";
Blockly.Msg["TEXT_CHARAT_TOOLTIP"] = "返回位于指定位置的字母。";
Blockly.Msg["TEXT_COUNT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#counting-substrings";
Blockly.Msg["TEXT_COUNT_MESSAGE0"] = "计算%1在%2里出现的次数";
Blockly.Msg["TEXT_COUNT_TOOLTIP"] = "计算在一段文本中，某个部分文本重复出现了多少次。";
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TOOLTIP"] = "将一个项添加到文本中。";
Blockly.Msg["TEXT_CREATE_JOIN_TITLE_JOIN"] = "加入";
Blockly.Msg["TEXT_CREATE_JOIN_TOOLTIP"] = "添加、移除或重新排列各节来重新配置这个文本块。";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_END"] = "到最后一个字符#";
Blockly.Msg["TEXT_GET_SUBSTRING_END_FROM_START"] = "至字符#";
Blockly.Msg["TEXT_GET_SUBSTRING_END_LAST"] = "到最后一个字符";
Blockly.Msg["TEXT_GET_SUBSTRING_HELPURL"] = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg["TEXT_GET_SUBSTRING_INPUT_IN_TEXT"] = "从文本";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FIRST"] = "取得子串自第一个字符";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_END"] = "取得子串自倒数#";
Blockly.Msg["TEXT_GET_SUBSTRING_START_FROM_START"] = "取得子串自#";
Blockly.Msg["TEXT_GET_SUBSTRING_TAIL"] = "-";
Blockly.Msg["TEXT_GET_SUBSTRING_TOOLTIP"] = "返回文本中指定的一部分。";
Blockly.Msg["TEXT_INDEXOF_HELPURL"] = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg["TEXT_INDEXOF_OPERATOR_FIRST"] = "寻找第一次出现的文本";
Blockly.Msg["TEXT_INDEXOF_OPERATOR_LAST"] = "寻找最后一次出现的文本";
Blockly.Msg["TEXT_INDEXOF_TITLE"] = "在文本 %1 里 %2  %3";
Blockly.Msg["TEXT_INDEXOF_TOOLTIP"] = "返回第一个文本段在第二个文本段中的第一/最后一个匹配项的起始位置。如果未找到，则返回%1。";
Blockly.Msg["TEXT_ISEMPTY_HELPURL"] = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg["TEXT_ISEMPTY_TITLE"] = "%1是空的";
Blockly.Msg["TEXT_ISEMPTY_TOOLTIP"] = "如果给定的文本为空，则返回真。";
Blockly.Msg["TEXT_JOIN_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg["TEXT_JOIN_TITLE_CREATEWITH"] = "建立文本从";
Blockly.Msg["TEXT_JOIN_TOOLTIP"] = "通过串起任意数量的项以建立一段文本。";
Blockly.Msg["TEXT_LENGTH_HELPURL"] = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg["TEXT_LENGTH_TITLE"] = "%1的长度";
Blockly.Msg["TEXT_LENGTH_TOOLTIP"] = "返回给定文本的字母数（包括空格）。";
Blockly.Msg["TEXT_PRINT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg["TEXT_PRINT_TITLE"] = "输出%1";
Blockly.Msg["TEXT_PRINT_TOOLTIP"] = "输出指定的文字、数字或其他值。";
Blockly.Msg["TEXT_PROMPT_HELPURL"] = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg["TEXT_PROMPT_TOOLTIP_NUMBER"] = "要求用户输入数字。";
Blockly.Msg["TEXT_PROMPT_TOOLTIP_TEXT"] = "要求用户输入一些文本。";
Blockly.Msg["TEXT_PROMPT_TYPE_NUMBER"] = "要求输入 数字 ，并显示提示消息";
Blockly.Msg["TEXT_PROMPT_TYPE_TEXT"] = "要求输入 文本 ，并显示提示消息";
Blockly.Msg["TEXT_REPLACE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#replacing-substrings";
Blockly.Msg["TEXT_REPLACE_MESSAGE0"] = "在%3中，将%1替换为%2";
Blockly.Msg["TEXT_REPLACE_TOOLTIP"] = "在一段文本中，将出现过的某部分文本都替换掉。";
Blockly.Msg["TEXT_REVERSE_HELPURL"] = "https://github.com/google/blockly/wiki/Text#reversing-text";
Blockly.Msg["TEXT_REVERSE_MESSAGE0"] = "翻转文本%1";
Blockly.Msg["TEXT_REVERSE_TOOLTIP"] = "将文本中各个字符的顺序倒转。";
Blockly.Msg["TEXT_TEXT_HELPURL"] = "https://zh.wikipedia.org/wiki/字符串";
Blockly.Msg["TEXT_TEXT_TOOLTIP"] = "一个字、词语或一行文本。";
Blockly.Msg["TEXT_TRIM_HELPURL"] = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg["TEXT_TRIM_OPERATOR_BOTH"] = "消除其两侧的空白";
Blockly.Msg["TEXT_TRIM_OPERATOR_LEFT"] = "消除其左侧的空白";
Blockly.Msg["TEXT_TRIM_OPERATOR_RIGHT"] = "消除其右侧的空白";
Blockly.Msg["TEXT_TRIM_TOOLTIP"] = "从某一端或同时从两端删除多余的空白，并返回这段文字的一个副本。";
Blockly.Msg["TODAY"] = "今天";
Blockly.Msg["UNDO"] = "撤销";
Blockly.Msg["UNNAMED_KEY"] = "匿名";
Blockly.Msg["VARIABLES_DEFAULT_NAME"] = "项目";
Blockly.Msg["VARIABLES_GET_CREATE_SET"] = "创建“设定%1”";
Blockly.Msg["VARIABLES_GET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg["VARIABLES_GET_TOOLTIP"] = "返回此变量的值。";
Blockly.Msg["VARIABLES_SET"] = "赋值 %1 为 %2";
Blockly.Msg["VARIABLES_SET_CREATE_GET"] = "创建“获得%1”";
Blockly.Msg["VARIABLES_SET_HELPURL"] = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg["VARIABLES_SET_TOOLTIP"] = "设置此变量，以使它和输入值相等。";
Blockly.Msg["VARIABLE_ALREADY_EXISTS"] = "名字叫“%1”的变量已经存在了。";
Blockly.Msg["VARIABLE_ALREADY_EXISTS_FOR_ANOTHER_TYPE"] = "名字叫“%1”的变量已经有了另一个类型：“%2”。";
Blockly.Msg["WORKSPACE_ARIA_LABEL"] = "Blockly工作区";
Blockly.Msg["WORKSPACE_COMMENT_DEFAULT_TEXT"] = "说点什么...";
Blockly.Msg["CONTROLS_FOREACH_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = Blockly.Msg["CONTROLS_IF_MSG_ELSEIF"];
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = Blockly.Msg["CONTROLS_IF_MSG_ELSE"];
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = Blockly.Msg["CONTROLS_IF_MSG_IF"];
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = Blockly.Msg["CONTROLS_REPEAT_INPUT_DO"];
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = Blockly.Msg["LISTS_INDEX_OF_HELPURL"];
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_INDEX_OF_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["LISTS_SET_INDEX_INPUT_IN_LIST"] = Blockly.Msg["LISTS_INLIST"];
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = Blockly.Msg["PROCEDURES_DEFNORETURN_COMMENT"];
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = Blockly.Msg["PROCEDURES_DEFNORETURN_DO"];
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_PROCEDURE"];
Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = Blockly.Msg["PROCEDURES_DEFNORETURN_TITLE"];
Blockly.Msg["TEXT_APPEND_VARIABLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];

Blockly.Msg["LOGIC_HUE"] = "210";
Blockly.Msg["LOOPS_HUE"] = "120";
Blockly.Msg["MATH_HUE"] = "230";
Blockly.Msg["TEXTS_HUE"] = "160";
Blockly.Msg["LISTS_HUE"] = "260";
Blockly.Msg["DICTIONARIES_HUE"] = "275";
Blockly.Msg["COLOUR_HUE"] = "20";
Blockly.Msg["TIME_HUE"] = "65";
Blockly.Msg["VARIABLES_HUE"] = "330";
Blockly.Msg["VARIABLES_DYNAMIC_HUE"] = "310";
Blockly.Msg["PROCEDURES_HUE"] = "290";
Blockly.Msg["GPIOIN_HUE"] = "180";
Blockly.Msg["GPIOOUT_HUE"] = "0";
Blockly.Msg["SENSEHAT_HUE"] = "40";
Blockly.Msg["CAMERA_HUE"] = "135";

Blockly.Msg["COLOUR_CONVERT_TITLE"] = "将颜色 %1 转成RGB列表"
Blockly.Msg["COLOUR_CONVERT_TOOLTIP"] = "将该颜色转化成RGB数值(0-255)组成的列表。"
Blockly.Msg["LISTS_EXTEND_TITLE"] = "在列表1 %1 末尾扩展列表2 %2";
Blockly.Msg["LISTS_EXTEND_TOOLTIP"] = "将列表2的所有元素添加到列表1的末尾。"
Blockly.Msg["TIME_SLEEP_TITLE"] = "等待%1秒";
Blockly.Msg["TIME_SLEEP_TOOLTIP"] = "等待一段时间。";
Blockly.Msg["TIME_STAMP_TITLE"] = "时间戳";
Blockly.Msg["TIME_STAMP_TOOLTIP"] = "返回当前时间戳。";
Blockly.Msg["TIME_TIME_STRUCT_TITLE"] = "当前%1";
Blockly.Msg["TIME_TIME_STRUCT_YEAR"] = "年";
Blockly.Msg["TIME_TIME_STRUCT_MON"] = "月";
Blockly.Msg["TIME_TIME_STRUCT_MDAY"] = "日";
Blockly.Msg["TIME_TIME_STRUCT_HOUR"] = "时";
Blockly.Msg["TIME_TIME_STRUCT_MIN"] = "分";
Blockly.Msg["TIME_TIME_STRUCT_SEC"] = "秒";
Blockly.Msg["TIME_TIME_STRUCT_WDAY"] = "是一周的第几天(0-6)";
Blockly.Msg["TIME_TIME_STRUCT_YDAY"] = "是一年的第几天";
Blockly.Msg["TIME_TIME_STRUCT_TOOLTIP"] = "返回当前时间/日期数据。";
Blockly.Msg["TIME_TIME_TITLE"] = "当前时间";
Blockly.Msg["TIME_TIME_TOOLTIP"] = "返回当前时间的字符串(HH:mm:ss).";
Blockly.Msg["TIME_DATE_TITLE"] = "当前日期";
Blockly.Msg["TIME_DATE_TOOLTIP"] = "返回当前日期的字符串(yyyy-MM-dd).";
Blockly.Msg["GPIO_DEVICES_IN_TITLE"] = "%1";
Blockly.Msg["GPIO_DEVICES_IN_TOOLTIP"] = "一个输入设备。";
Blockly.Msg["GPIO_INPUT_DIGITAL_TITLE"] = "设置GPIO%1为数字输入%2";
Blockly.Msg["GPIO_INPUT_DIGITAL_TOOLTIP"] = "设置一个GPIO端口为数字输入，使用BCM编码。";
Blockly.Msg["GPIO_INPUT_SMOOTHED_TITLE"] = "设置GPIO%1为平滑输入%2";
Blockly.Msg["GPIO_INPUT_SMOOTHED_TOOLTIP"] = "设置一个GPIO端口为平滑输入，使用BCM编码。";
Blockly.Msg["GPIO_BUTTON_TITLE"] = "设置GPIO%1为按钮%2";
Blockly.Msg["GPIO_BUTTON_TOOLTIP"] = "设置一个GPIO端口连接到一个按钮。";
Blockly.Msg["GPIO_LINESENSOR_TITLE"] = "设置GPIO%1为循迹传感器%2";
Blockly.Msg["GPIO_LINESENSOR_TOOLTIP"] = "设置一个GPIO端口连接到一个循迹传感器(红外接近传感器)。";
Blockly.Msg["GPIO_MOTIONSENSOR_TITLE"] = "设置GPIO%1为运动传感器%2";
Blockly.Msg["GPIO_MOTIONSENSOR_TOOLTIP"] = "设置一个GPIO端口连接到一个无源红外运动传感器。";
Blockly.Msg["GPIO_LIGHTSENSOR_TITLE"] = "设置GPIO%1为光线传感器%2";
Blockly.Msg["GPIO_LIGHTSENSOR_TOOLTIP"] = "设置一个GPIO端口连接到一个光线传感器(光敏电阻)。";
Blockly.Msg["GPIO_DISTANCESENSOR_TITLE"] = "设置GPIO%1(echo)%2(trigger)为距离传感器%3";
Blockly.Msg["GPIO_DISTANCESENSOR_TOOLTIP"] = "设置两个GPIO端口连接到一个超声波距离传感器(HC-SR04)，一个接echo一个接trigger。最大可测距离为1米。";
Blockly.Msg["GPIO_INPUT_VALUE_TITLE"] = "%1的值";
Blockly.Msg["GPIO_INPUT_VALUE_TOOLTIP"] = "返回一个代表设备状态的值。通常是一个布尔值或者一个0到1之间的数字。对于距离传感器，单位是米。";
Blockly.Msg["GPIO_CLOSE_IN_TITLE"] = "关闭%1并释放端口";
Blockly.Msg["GPIO_CLOSE_IN_TOOLTIP"] = "关闭设备并释放所有关联资源。";
Blockly.Msg["GPIO_DEVICES_OUT_TITLE"] = "%1";
Blockly.Msg["GPIO_DEVICES_OUT_TOOLTIP"] = "一个输出设备。";
Blockly.Msg["GPIO_OUTPUT_TITLE"] = "设置GPIO%1为数字输出%2";
Blockly.Msg["GPIO_OUTPUT_TOOLTIP"] = "设置一个GPIO端口为数字输出，使用BCM编码。";
Blockly.Msg["GPIO_LED_TITLE"] = "设置GPIO%1为LED%2";
Blockly.Msg["GPIO_LED_TOOLTIP"] = "设置一个GPIO端口连接到一个LED灯。";
Blockly.Msg["GPIO_BUZZER_TITLE"] = "设置GPIO%1为蜂鸣器%2";
Blockly.Msg["GPIO_BUZZER_TOOLTIP"] = "设置一个GPIO端口连接到一个有源蜂鸣器。";
Blockly.Msg["GPIO_OUTPUT_ON_TITLE"] = "开启%1";
Blockly.Msg["GPIO_OUTPUT_ON_TOOLTIP"] = "开启该设备。";
Blockly.Msg["GPIO_OUTPUT_OFF_TITLE"] = "关闭%1";
Blockly.Msg["GPIO_OUTPUT_OFF_TOOLTIP"] = "关闭该设备。";
Blockly.Msg["GPIO_OUTPUT_TOGGLE_TITLE"] = "反转%1的输出";
Blockly.Msg["GPIO_OUTPUT_TOGGLE_TOOLTIP"] = "反转该设备的输出。";
Blockly.Msg["GPIO_CLOSE_OUT_TITLE"] = Blockly.Msg["GPIO_CLOSE_IN_TITLE"];
Blockly.Msg["GPIO_CLOSE_OUT_TOOLTIP"] = Blockly.Msg["GPIO_CLOSE_IN_TOOLTIP"];
Blockly.Msg["GPIO_RGBLED_TITLE"] = "设置GPIO %1 %2 %3为RGB LED%4";
Blockly.Msg["GPIO_RGBLED_TOOLTIP"] = "设置三个GPIO端口(分别为红、绿、蓝)连接到一个RGB LED灯。";
Blockly.Msg["GPIO_RGBLED_COLOUR_TITLE"] = "设置%1颜色为%2";
Blockly.Msg["GPIO_RGBLED_COLOUR_TOOLTIP"] = "设置RGB LED灯的颜色。";
Blockly.Msg["GPIO_PWM_TITLE"] = "设置GPIO%1为PWM输出%2";
Blockly.Msg["GPIO_PWM_TOOLTIP"] = "设置一个GPIO端口为PWM输出，使用BCM编码。";
Blockly.Msg["GPIO_PWM_BREATH_TITLE"] = "设置%1为呼吸灯，点亮时长：%2熄灭时长：%3淡入时长：%4淡出时长：%5闪烁次数：%6";
Blockly.Msg["GPIO_PWM_BREATH_TOOLTIP"] = "设置该PWM设备成呼吸灯。如果闪烁次数为空，设备将一直闪烁。";
Blockly.Msg["GPIO_PWM_DC_TITLE"] = "设置%1占空比为%2 %%";
Blockly.Msg["GPIO_PWM_DC_TOOLTIP"] = "设置该PWM设备的占空比（按百分比）。";
Blockly.Msg["GPIO_PWM_FREQUENCY_TITLE"] = "设置%1频率为%2 Hz";
Blockly.Msg["GPIO_PWM_FREQUENCY_TOOLTIP"] = "设置该PWM设备的频率（单位Hz）。";
Blockly.Msg["GPIO_OUTPUT_VALUE_TITLE"] = Blockly.Msg["GPIO_INPUT_VALUE_TITLE"];
Blockly.Msg["GPIO_OUTPUT_VALUE_TOOLTIP"] = "返回一个代表设备状态的值。通常是一个布尔值或者一个0到1之间的数字。对于PWM设备，该值是占空比。";
Blockly.Msg["GPIO_OUTPUT_VALUE_SET_TITLE"] = "设置%1的值为%2";
Blockly.Msg["GPIO_OUTPUT_VALUE_SET_TOOLTIP"] = "设置改设备的输出值并改变其状态，可用值为一个布尔值或者一个0到1之间的数字。";
Blockly.Msg["SENSEHAT_INITIALIZE_TITLE"] = "初始化Sense HAT。仿真：%1";
Blockly.Msg["SENSEHAT_INITIALIZE_TOOLTIP"] = "初始化Sense HAT并选择是否使用仿真器。";
Blockly.Msg["SENSEHAT_SET_ROTATION_TITLE"] = "设置旋转%1";
Blockly.Msg["SENSEHAT_SET_ROTATION_TOOLTIP"] = "旋转LED点阵屏，0°代表树莓派HDMI接口朝下的方向。";
Blockly.Msg["SENSEHAT_FLIP_H_TITLE"] = "水平翻转";
Blockly.Msg["SENSEHAT_FLIP_H_TOOLTIP"] = "水平翻转LED点阵屏上的图案。";
Blockly.Msg["SENSEHAT_FLIP_V_TITLE"] = "垂直翻转";
Blockly.Msg["SENSEHAT_FLIP_V_TOOLTIP"] = "垂直翻转LED点阵屏上的图案。";
Blockly.Msg["SENSEHAT_PIXELS_TOOLTIP"] = "为LED点阵屏返回一个包含64个像素点颜色的列表。";
Blockly.Msg["SENSEHAT_SET_PIXELS_TITLE"] = "显示图案%1";
Blockly.Msg["SENSEHAT_SET_PIXELS_TOOLTIP"] = "基于一个64个像素点颜色的列表更新点阵屏的显示。";
Blockly.Msg["SENSEHAT_SET_PIXEL_TITLE"] = "设置像素点X: %1 Y: %2的颜色为%3";
Blockly.Msg["SENSEHAT_SET_PIXEL_TOOLTIP"] = "设置点阵屏上位于指定的X-Y坐标的一个像素点为指定的颜色。(0,0)代表左上角的像素点。";
Blockly.Msg["SENSEHAT_LOAD_IMAGE_TITLE"] = "显示图片%1";
Blockly.Msg["SENSEHAT_LOAD_IMAGE_TOOLTIP"] = "从指定路径载入图片文件并显示在点阵屏上。图片大小必须是8x8像素。";
Blockly.Msg["SENSEHAT_CLEAR_TITLE"] = "清空LED点阵屏%1";
Blockly.Msg["SENSEHAT_CLEAR_TOOLTIP"] = "设置整个LED点阵屏显示单色，默认为空/关闭。";
Blockly.Msg["SENSEHAT_SHOW_MESSAGE_TITLE"] = "显示消息%1滚动速度%2文字颜色%3背景颜色%4";
Blockly.Msg["SENSEHAT_SHOW_MESSAGE_TOOLTIP"] = "以指定的速度、文字颜色和背景颜色在点阵屏上从右往左滚动显示一条指定的文本消息。";
Blockly.Msg["SENSEHAT_SHOW_LETTER_TITLE"] = "显示字符%1文字颜色%2背景颜色%3";
Blockly.Msg["SENSEHAT_SHOW_LETTER_TOOLTIP"] = "在LED点阵屏上显示单一字符(ASCII)。";
Blockly.Msg["SENSEHAT_LOW_LIGHT_TITLE"] = "切换低亮度模式%1";
Blockly.Msg["SENSEHAT_LOW_LIGHT_TOOLTIP"] = "切换LED点阵屏为低亮度模式，当Sense HAT在黑暗环境时很有用。";
Blockly.Msg["SENSEHAT_GET_HUMIDITY_TITLE"] = "获取湿度";
Blockly.Msg["SENSEHAT_GET_HUMIDITY_TOOLTIP"] = "从湿度传感器获取相对湿度(百分比)。";
Blockly.Msg["SENSEHAT_GET_TEMPERATURE_TITLE"] = "获取温度";
Blockly.Msg["SENSEHAT_GET_TEMPERATURE_TOOLTIP"] = "从湿度传感器获取当前温度(摄氏度)。";
Blockly.Msg["SENSEHAT_GET_PRESSURE_TITLE"] = "获取气压";
Blockly.Msg["SENSEHAT_GET_PRESSURE_TOOLTIP"] = "从压力传感器获取当前气压(毫巴)。";
Blockly.Msg["SENSEHAT_SET_IMU_CONFIG_TITLE"] = "启用罗盘%1陀螺仪%2加速度计%3";
Blockly.Msg["SENSEHAT_SET_IMU_CONFIG_TOOLTIP"] = "启用或禁用陀螺仪、加速度计和磁力计。";
Blockly.Msg["SENSEHAT_GET_ORIENTATION_TITLE"] = "获取方向数据";
Blockly.Msg["SENSEHAT_GET_ORIENTATION_TOOLTIP"] = "使用飞行器的俯仰、横滚和偏航轴系，以度为单位获取当前方向。";
Blockly.Msg["SENSEHAT_GET_COMPASS_TITLE"] = "获取罗盘数据";
Blockly.Msg["SENSEHAT_GET_COMPASS_TOOLTIP"] = "从磁力计获取以度为单位的北方向角。";
Blockly.Msg["SENSEHAT_GET_GYROSCOPE_TITLE"] = "获取陀螺仪数据";
Blockly.Msg["SENSEHAT_GET_GYROSCOPE_TOOLTIP"] = "仅使用陀螺仪，使用飞行器的俯仰、横滚和偏航轴系，以度为单位获取当前方向。";
Blockly.Msg["SENSEHAT_GET_ACCELEROMETER_TITLE"] = "获取加速度计数据";
Blockly.Msg["SENSEHAT_GET_ACCELEROMETER_TOOLTIP"] = "以G为单位，获取x、y、z三个轴方向的加速度。";
Blockly.Msg["SENSEHAT_WAIT_FOR_EVENT_TITLE"] = "等待摇杆事件";
Blockly.Msg["SENSEHAT_WAIT_FOR_EVENT_TOOLTIP"] = "阻塞程序直到发生摇杆事件。";
Blockly.Msg["SENSEHAT_EVENT_TIMESTAMP_TITLE"] = "获取摇杆事件时间戳";
Blockly.Msg["SENSEHAT_EVENT_TIMESTAMP_TOOLTIP"] = "返回摇杆事件发生的时间。";
Blockly.Msg["SENSEHAT_EVENT_DIRECTION_TITLE"] = "获取摇杆事件方向";
Blockly.Msg["SENSEHAT_EVENT_DIRECTION_TOOLTIP"] = "返回摇杆被按下的方向，一个字符串('up', 'down', 'left', 'right', 'middle')。";
Blockly.Msg["SENSEHAT_EVENT_ACTION_TITLE"] = "获取摇杆事件动作";
Blockly.Msg["SENSEHAT_EVENT_ACTION_TOOLTIP"] = "返回发生的摇杆动作，一个字符串('pressed', 'released', 'held')。";
Blockly.Msg["SENSEHAT_GET_EVENTS_TITLE"] = "获取摇杆事件";
Blockly.Msg["SENSEHAT_GET_EVENTS_TOOLTIP"] = "返回一个元组组成的列表，包含自从'获取摇杆事件'或'等待摇杆事件'被调用以来发生的所有事件。";
Blockly.Msg["SENSEHAT_JOYSTICK_PUSHED_TITLE"] = "当摇杆被推向%1方向%2执行%3";
Blockly.Msg["SENSEHAT_JOYSTICK_PUSHED_ANY"] = "任意";
Blockly.Msg["SENSEHAT_JOYSTICK_PUSHED_LEFT"] = "左";
Blockly.Msg["SENSEHAT_JOYSTICK_PUSHED_UP"] = "上";
Blockly.Msg["SENSEHAT_JOYSTICK_PUSHED_RIGHT"] = "右";
Blockly.Msg["SENSEHAT_JOYSTICK_PUSHED_DOWN"] = "下";
Blockly.Msg["SENSEHAT_JOYSTICK_PUSHED_MIDDLE"] = "中间";
Blockly.Msg["SENSEHAT_JOYSTICK_PUSHED_TOOLTIP"] = "当摇杆被推向一个方向，执行一些语句。";
Blockly.Msg["DICTIONARIES_CREATE_EMPTY_TITLE"] = "创建空字典";
Blockly.Msg["DICTIONARIES_CREATE_EMPTY_TOOLTIP"] = "返回一个字典，长度为 0，不包含任何数据记录。";
Blockly.Msg["DICTIONARIES_CREATE_WITH_CONTAINER_TITLE_VALUE"] = "字典";
Blockly.Msg["DICTIONARIES_CREATE_WITH_CONTAINER_TOOLTIP"] = "增加、删除或重新排列各部分以此重新配置这个字典块。";
Blockly.Msg["DICTIONARIES_CREATE_WITH_INPUT_WITH"] = "建立字典从";
Blockly.Msg["DICTIONARIES_CREATE_WITH_INPUT_KEY"] = "键"
Blockly.Msg["DICTIONARIES_CREATE_WITH_INPUT_VALUE"] = "值"
Blockly.Msg["DICTIONARIES_CREATE_WITH_ITEM_TITLE"] = Blockly.Msg["VARIABLES_DEFAULT_NAME"];
Blockly.Msg["DICTIONARIES_CREATE_WITH_ITEM_TOOLTIP"] = "将一个键值对添加到字典中。";
Blockly.Msg["DICTIONARIES_CREATE_WITH_TOOLTIP"] = "建立一个具有任意数量键值对的字典。";
Blockly.Msg["DICTIONARIES_LENGTH_TITLE"] = "%1的长度"
Blockly.Msg["DICTIONARIES_LENGTH_TOOLTIP"] = "返回字典的长度（键值对数）。"
Blockly.Msg["DICTIONARIES_CREATE_WITH_LIST_TITLE"] = "建立字典使用键列表%1值%2"
Blockly.Msg["DICTIONARIES_CREATE_WITH_LIST_TOOLTIP"] = "使用一个键列表和一个默认值建立字典。"
Blockly.Msg["DICTIONARIES_ISEMPTY_TITLE"] = "%1是空的"
Blockly.Msg["DICTIONARIES_ISEMPTY_TOOLTIP"] = "如果该字典为空，则返回真。"
Blockly.Msg["DICTIONARIES_UPDATE_TITLE"] = "更新字典1%1使用字典2%2"
Blockly.Msg["DICTIONARIES_UPDATE_TOOLTIP"] = "使用字典2更新字典1的内容，新的键值会被添加，相同的键其值会被更新。"
Blockly.Msg["DICTIONARIES_SET_KEY_TITLE"] = "在字典中%1设置键%2值为%3"
Blockly.Msg["DICTIONARIES_SET_KEY_TOOLTIP"] = "设置在字典中指定键的值。"
Blockly.Msg["DICTIONARIES_GET_KEY_DICT"] = "在字典中"
Blockly.Msg["DICTIONARIES_GET_KEY"] = "取得 值从键"
Blockly.Msg["DICTIONARIES_POP_KEY"] = "取得并移除 值从键"
Blockly.Msg["DICTIONARIES_DEL_KEY"] = "移除 值从键"
Blockly.Msg["DICTIONARIES_GET_KEY_TOOLTIP"] = "从字典中返回指定键的值。"
Blockly.Msg["DICTIONARIES_POP_KEY_TOOLTIP"] = "从字典中移除并返回指定键的值。"
Blockly.Msg["DICTIONARIES_DEL_KEY_TOOLTIP"] = "从字典中移除指定键。"
Blockly.Msg["DICTIONARIES_KEYS_DICT"] = "在字典中"
Blockly.Msg["DICTIONARIES_KEYS_KEY"] = "取得 键 列表"
Blockly.Msg["DICTIONARIES_KEYS_VALUE"] = "取得 值 列表"
Blockly.Msg["DICTIONARIES_KEYS_TOOLTIP"] = "返回字典中所有键组成的列表。"
Blockly.Msg["DICTIONARIES_VALUES_TOOLTIP"] = "返回字典中所有值组成的列表。"
Blockly.Msg["DICTIONARIES_KEY_IN_TITLE"] = "键%1 %2字典%3中"
Blockly.Msg["DICTIONARIES_KEY_IN"] = "在"
Blockly.Msg["DICTIONARIES_KEY_NOT_IN"] = "不在"
Blockly.Msg["DICTIONARIES_KEY_IN_TOOLTIP"] = "判断指定键是否存在于字典中。"
Blockly.Msg["TUBE_INITIALIZE_TITLE"] = "设置GPIO%1(CLK)%2(DIO)为数码管%3亮度%4小数点%5"
Blockly.Msg["TUBE_INITIALIZE_TOOLTIP"] = "连接一个带TM1637控制器的四位七段数码管到2个GPIO端口，设置亮度0-7，如果数码管有小数点，勾选小数点。"
Blockly.Msg["TUBE_BRIGHTNESS_TITLE"] = "设置%1亮度%2"
Blockly.Msg["TUBE_BRIGHTNESS_TOOLTIP"] = "设置显示亮度，范围0-7。"
Blockly.Msg["TUBE_WRITE_TITLE"] = "%1显示%2偏移%3"
Blockly.Msg["TUBE_WRITE_TOOLTIP"] = "显示字符或数字，从最左位偏移0-3个位置。"
Blockly.Msg["TUBE_NUMBER_TITLE"] = "%1显示数字%2"
Blockly.Msg["TUBE_NUMBER_TOOLTIP"] = "显示从-999到9999直接的数值，右对齐。"
Blockly.Msg["TUBE_NUMBERS_TITLE"] = "%1显示数字%2:%3 %4"
Blockly.Msg["TUBE_NUMBERS_TOOLTIP"] = "显示两个从-9到99的数值，有补位0，可选是否显示中间的冒号。"
Blockly.Msg["TUBE_TEMPERATURE_TITLE"] = "%1显示温度%2℃"
Blockly.Msg["TUBE_TEMPERATURE_TOOLTIP"] = "显示摄氏温度数值，范围-9到99。"
Blockly.Msg["TUBE_SHOW_TITLE"] = "%1显示文本%2"
Blockly.Msg["TUBE_SHOW_TOOLTIP"] = "显示字符串，不多于4个字符。"
Blockly.Msg["TUBE_SCROLL_TITLE"] = "%1滚动文本%2延时%3毫秒"
Blockly.Msg["TUBE_SCROLL_TOOLTIP"] = "按给定延时从右往左滚动显示字符串, 250毫秒对应每秒4帧。"
Blockly.Msg["TUBE_CLEAR_TITLE"] = "清空数码管%1"
Blockly.Msg["TUBE_CLEAR_TOOLTIP"] = "清空数码管显示的内容。"
Blockly.Msg["CAMERA_ENABLE_TITLE"] = "%1摄像头"
Blockly.Msg["CAMERA_ENABLE_ENABLE"] = "启用"
Blockly.Msg["CAMERA_ENABLE_STOP"] = "停用"
Blockly.Msg["CAMERA_ENABLE_TOOLTIP"] = "启用或停用摄像头模块。"
Blockly.Msg["CAMERA_PREVIEW_TITLE"] = "%1预览"
Blockly.Msg["CAMERA_PREVIEW_OPEN"] = "打开"
Blockly.Msg["CAMERA_PREVIEW_CLOSE"] = "关闭"
Blockly.Msg["CAMERA_PREVIEW_TOOLTIP"] = "打开或关闭摄像头预览窗口。"
Blockly.Msg["CAMERA_CAPTURE_TITLE"] = "拍摄照片%1.%2"
Blockly.Msg["CAMERA_CAPTURE_TOOLTIP"] = "用摄像头拍摄一张照片，以指定的格式保存在指定的路径/文件名。"
Blockly.Msg["CAMERA_RECORD_TITLE"] = "摄制视频%1.h264"
Blockly.Msg["CAMERA_RECORD_TOOLTIP"] = "用摄像头开始拍摄视频，以h264格式保存在指定的路径/文件名。"
Blockly.Msg["CAMERA_STOP_RECORDING_TITLE"] = "停止摄制视频"
Blockly.Msg["CAMERA_STOP_RECORDING_TOOLTIP"] = "停止拍摄视频。"
Blockly.Msg["CAMERA_WEB_STREAM_TITLE"] = "开始网络视频直播，端口:%1"
Blockly.Msg["CAMERA_WEB_STREAM_TOOLTIP"] = "在你的树莓派IP地址和指定端口开启HTTP视频直播流。使用任意浏览器或者视频播放器打开链接http://树莓派IP:端口/stream.mjpg来观看直播。"
Blockly.Msg["CAMERA_RESOLUTION_TITLE"] = "设置摄像头分辨率%1x%2"
Blockly.Msg["CAMERA_RESOLUTION_TOOLTIP"] = "设置拍照、录像和预览的分辨率。"
Blockly.Msg["CAMERA_FLIP_TITLE"] = "%1翻转摄像头"
Blockly.Msg["CAMERA_FLIP_H"] = "水平"
Blockly.Msg["CAMERA_FLIP_V"] = "垂直"
Blockly.Msg["CAMERA_FLIP_TOOLTIP"] = "设置是否水平/垂直翻转摄像头的输出。"
Blockly.Msg["CAMERA_ROTATE_TITLE"] = "旋转摄像头%1"
Blockly.Msg["CAMERA_ROTATE_TOOLTIP"] = "设置当前摄像头图像的旋转方向。"
Blockly.Msg["CAMERA_FRAMERATE_TITLE"] = "设置摄像头帧率%1"
Blockly.Msg["CAMERA_FRAMERATE_TOOLTIP"] = "设置录像和预览的帧率(FPS)。"
Blockly.Msg["CAMERA_ANNOTATE_TEXT_TITLE"] = "添加注释文本%1"
Blockly.Msg["CAMERA_ANNOTATE_TEXT_TOOLTIP"] = "为所有输出添加一段注释文本。只允许最多32个ASCII字符。"
Blockly.Msg["CAMERA_ANNOTATE_SIZE_TITLE"] = "设置注释大小%1"
Blockly.Msg["CAMERA_ANNOTATE_SIZE_TOOLTIP"] = "设置注释文本的字体大小。"
Blockly.Msg["CAMERA_ANNOTATE_COLOUR_TITLE"] = "设置注释%1颜色%2"
Blockly.Msg["CAMERA_ANNOTATE_COLOUR_FOREGROUND"] = "文本"
Blockly.Msg["CAMERA_ANNOTATE_COLOUR_BACKGROUND"] = "背景"
Blockly.Msg["CAMERA_ANNOTATE_COLOUR_TOOLTIP"] = "设置注释文本的亮度或者背景的颜色。"
Blockly.Msg["CAMERA_ISO_TITLE"] = "设置ISO%1"
Blockly.Msg["CAMERA_ISO_AUTO"] = "自动"
Blockly.Msg["CAMERA_ISO_TOOLTIP"] = "设置摄像头的ISO数值。"
Blockly.Msg["CAMERA_SHUTTER_SPEED_TITLE"] = "设置快门速度%1微秒"
Blockly.Msg["CAMERA_SHUTTER_SPEED_TOOLTIP"] = "设置摄像头的快门速度，单位微秒。"
Blockly.Msg["CAMERA_BRIGHTNESS_TITLE"] = "设置图像亮度%1"
Blockly.Msg["CAMERA_BRIGHTNESS_TOOLTIP"] = "设置摄像头的亮度设置(0~100)。"
Blockly.Msg["CAMERA_SHARPNESS_TITLE"] = "设置图像锐度%1"
Blockly.Msg["CAMERA_SHARPNESS_TOOLTIP"] = "设置摄像头的锐度设置(-100~100)。"
Blockly.Msg["CAMERA_CONTRAST_TITLE"] = "设置图像对比度%1"
Blockly.Msg["CAMERA_CONTRAST_TOOLTIP"] = "设置摄像头的对比度设置(-100~100)。"
Blockly.Msg["CAMERA_SATURATION_TITLE"] = "设置图像饱和度%1"
Blockly.Msg["CAMERA_SATURATION_TOOLTIP"] = "设置摄像头的饱和度设置(-100~100)。"
Blockly.Msg["CAMERA_AWB_MODE_TITLE"] = "设置自动白平衡模式%1"
Blockly.Msg["CAMERA_AWB_MODE_AUTO"] = "自动"
Blockly.Msg["CAMERA_AWB_MODE_SUNLIGHT"] = "日光"
Blockly.Msg["CAMERA_AWB_MODE_CLOUDY"] = "多云"
Blockly.Msg["CAMERA_AWB_MODE_SHADE"] = "阴影"
Blockly.Msg["CAMERA_AWB_MODE_TUNGSTEN"] = "钨丝灯"
Blockly.Msg["CAMERA_AWB_MODE_INCANDESCENT"] = "白炽灯"
Blockly.Msg["CAMERA_AWB_MODE_FLUORESCENT"] = "荧光灯"
Blockly.Msg["CAMERA_AWB_MODE_FLASH"] = "闪光灯"
Blockly.Msg["CAMERA_AWB_MODE_HORIZON"] = "地平线"
Blockly.Msg["CAMERA_AWB_MODE_TOOLTIP"] = "设置摄像头的自动白平衡模式。"
Blockly.Msg["CAMERA_EXPOSURE_COMPENSATION_TITLE"] = "设置曝光补偿%1"
Blockly.Msg["CAMERA_EXPOSURE_COMPENSATION_TOOLTIP"] = "设置摄像头的曝光补偿水平(-25~25)。"
Blockly.Msg["CAMERA_EXPOSURE_MODE_TITLE"] = "设置曝光模式%1"
Blockly.Msg["CAMERA_EXPOSURE_MODE_AUTO"] = "自动"
Blockly.Msg["CAMERA_EXPOSURE_MODE_NIGHT"] = "夜间"
Blockly.Msg["CAMERA_EXPOSURE_MODE_NIGHTPREVIEW"] = "夜间预览"
Blockly.Msg["CAMERA_EXPOSURE_MODE_BACKLIGHT"] = "逆光"
Blockly.Msg["CAMERA_EXPOSURE_MODE_SPOTLIGHT"] = "聚光灯"
Blockly.Msg["CAMERA_EXPOSURE_MODE_SPORTS"] = "运动"
Blockly.Msg["CAMERA_EXPOSURE_MODE_SNOW"] = "雪景"
Blockly.Msg["CAMERA_EXPOSURE_MODE_BEACH"] = "沙滩"
Blockly.Msg["CAMERA_EXPOSURE_MODE_VERYLONG"] = "长曝光"
Blockly.Msg["CAMERA_EXPOSURE_MODE_FIXEDFPS"] = "固定帧率"
Blockly.Msg["CAMERA_EXPOSURE_MODE_ANTISHAKE"] = "防抖"
Blockly.Msg["CAMERA_EXPOSURE_MODE_FIREWORKS"] = "烟火"
Blockly.Msg["CAMERA_EXPOSURE_MODE_TOOLTIP"] = "设置摄像头的曝光模式。"
Blockly.Msg["CAMERA_METER_MODE_TITLE"] = "设置测光模式%1"
Blockly.Msg["CAMERA_METER_MODE_AVERAGE"] = "平均测光"
Blockly.Msg["CAMERA_METER_MODE_SPOT"] = "点测光"
Blockly.Msg["CAMERA_METER_MODE_BACKLIT"] = "模拟背光"
Blockly.Msg["CAMERA_METER_MODE_MATRIX"] = "矩阵测光"
Blockly.Msg["CAMERA_METER_MODE_TOOLTIP"] = "设置摄像头的测光模式。"
Blockly.Msg["CAMERA_IMAGE_EFFECT_TITLE"] = "设置图像特效%1"
Blockly.Msg["CAMERA_IMAGE_EFFECT_NONE"] = "无"
Blockly.Msg["CAMERA_IMAGE_EFFECT_NEGATIVE"] = "负片"
Blockly.Msg["CAMERA_IMAGE_EFFECT_SOLARIZE"] = "过曝"
Blockly.Msg["CAMERA_IMAGE_EFFECT_SKETCH"] = "素描"
Blockly.Msg["CAMERA_IMAGE_EFFECT_DENOISE"] = "降噪"
Blockly.Msg["CAMERA_IMAGE_EFFECT_EMBOSS"] = "浮雕"
Blockly.Msg["CAMERA_IMAGE_EFFECT_OILPAINT"] = "油画"
Blockly.Msg["CAMERA_IMAGE_EFFECT_HATCH"] = "网格"
Blockly.Msg["CAMERA_IMAGE_EFFECT_GPEN"] = "G笔"
Blockly.Msg["CAMERA_IMAGE_EFFECT_PASTEL"] = "粉彩"
Blockly.Msg["CAMERA_IMAGE_EFFECT_WATERCOLOR"] = "水彩"
Blockly.Msg["CAMERA_IMAGE_EFFECT_FILM"] = "胶片"
Blockly.Msg["CAMERA_IMAGE_EFFECT_BLUR"] = "模糊"
Blockly.Msg["CAMERA_IMAGE_EFFECT_SATURATION"] = "饱和"
Blockly.Msg["CAMERA_IMAGE_EFFECT_COLORSWAP"] = "换色"
Blockly.Msg["CAMERA_IMAGE_EFFECT_WASHEDOUT"] = "冲刷"
Blockly.Msg["CAMERA_IMAGE_EFFECT_POSTERISE"] = "色彩分离"
Blockly.Msg["CAMERA_IMAGE_EFFECT_COLORPOINT"] = "重点色"
Blockly.Msg["CAMERA_IMAGE_EFFECT_COLORBALANCE"] = "色彩均衡"
Blockly.Msg["CAMERA_IMAGE_EFFECT_CARTOON"] = "卡通"
Blockly.Msg["CAMERA_IMAGE_EFFECT_DEINTERLACE1"] = "反交错1"
Blockly.Msg["CAMERA_IMAGE_EFFECT_DEINTERLACE2"] = "反交错2"
Blockly.Msg["CAMERA_IMAGE_EFFECT_TOOLTIP"] = "设置摄像头应用的图像特效。"