var MSG = {
  alert: "Alert",
  confirm: "Confirm",
  prompt: "Prompt",
  title: "Code Editor",
  blocks: "Blocks",
  outputs: "Code outputs:",
  defaultName: "NewProject",
  nameTooltip: "Input the project's name.",
  openTooltip: "Open a XML code file.",
  saveTooltip: "Save the code to a XML file.",
  runTooltip: "Run the program defined by the blocks in the workspace.",
  stopTooltip: "Stop the program.",
  badCode: "Program error:\n%1",
  codeEnd: "Program ended\n",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",
  clearOutputTooltip: "Clear all outputs.",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catDictionaries: "Dictionaries",
  catColour: "Colour",
  catTime: "Time",
  catVariables: "Variables",
  catFunctions: "Functions",
  catRaspberryPi: "Raspberry Pi",
  catGPIOin: "GPIO IN",
  catGPIOout: "GPIO OUT",
  catTube: "Digital Tube",
  catPicamera: "Picamera",
  catPicameraPro: "Professional Mode",
  listVariable: "list",
  textVariable: "text",
  deviceVariable: "device",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  typeError: "You are not loading a XML file!",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML."
};
