var MSG = {
  alert: "警告",
  confirm: "确认",
  prompt: "提示",
  title: "代码编辑器",
  blocks: "积木",
  outputs: "程序输出：",
  openTooltip: "打开 XML 程序文件。",
  saveTooltip: "将程序保存到 XML 文件。",
  runTooltip: "运行工作区中积木块所定义的程序。",
  stopTooltip: "停止运行程序。",
  badCode: "程序错误：\n%1",
  codeEnd: "程序结束\n",
  timeout: "超过最大执行行数。",
  trashTooltip: "删除所有块。",
  clearOutputTooltip: "清空所有输出内容。",
  catLogic: "逻辑",
  catLoops: "循环",
  catMath: "数学",
  catText: "文本",
  catLists: "列表",
  catDictionaries: "字典",
  catColour: "颜色",
  catTime: "时间",
  catVariables: "变量",
  catFunctions: "函数",
  catRaspberryPi: "树莓派",
  catGPIOin: "通用输入",
  catGPIOout: "通用输出",
  catTube: "数码管",
  catPicamera: "摄像头",
  catPicameraPro: "专业模式",
  listVariable: "列表",
  textVariable: "文本",
  deviceVariable: "设备",
  httpRequestError: "请求存在问题。",
  linkAlert: "通过这个链接分享您的模块：\n\n%1",
  hashError: "对不起，没有任何已保存的程序对应'%1' 。",
  xmlError: "无法载入您保存的文件。您是否使用其他版本的Blockly创建该文件的？",
  badXml: "XML解析错误：\n%1\n\n选择“确定”以取消您对XML的修改，或选择“取消”以继续编辑XML。"
};