var MSG = {
  alert: "警告",
  confirm: "確認",
  prompt: "提示",
  title: "程式編輯器",
  blocks: "積木",
  outputs: "程式輸出：",
  openTooltip: "打開 XML 程式檔案。",
  saveTooltip: "將程式保存到 XML 檔案。",
  runTooltip: "執行工作區中積木組所定義的程式。",
  stopTooltip: "停止執行程式。",
  badCode: "程式錯誤：\n%1",
  codeEnd: "程式結束\n",
  timeout: "超過最大執行數。",
  trashTooltip: "捨棄所有積木。",
  clearOutputTooltip: "清空所有輸出內容。",
  catLogic: "邏輯",
  catLoops: "迴圈",
  catMath: "數學式",
  catText: "文字",
  catLists: "清單",
  catDictionaries: "字典",
  catColour: "顏色",
  catTime: "時間",
  catVariables: "變量",
  catFunctions: "流程",
  catRaspberryPi: "樹莓派",
  catGPIOin: "通用輸入",
  catGPIOout: "通用輸出",
  catTube: "數碼管",
  catPicamera: "攝像頭",
  catPicameraPro: "專業模式",
  listVariable: "清單",
  textVariable: "文字",
  deviceVariable: "設備",
  httpRequestError: "命令出現錯誤。",
  linkAlert: "透過此連結分享您的積木組：\n\n%1",
  hashError: "對不起，「%1」並未對應任何已保存的程式。",
  xmlError: "未能載入您保存的檔案。或許它是由其他版本的Blockly創建？",
  badXml: "解析 XML 時出現錯誤：\n%1\n\n選擇'確定'以放棄您的更改，或選擇'取消'以進一步編輯 XML。"
};